In [1]:
import pandas as pd

In [2]:
products_df = pd.read_csv("Products.csv")
products_df

,id,name,item_type,price,vat_rate,category,organization_id,org_unit_id,created_date,last_modified_date,created_by,last_modified_by,is_overridden
0,1,"NESTEA CITRÓN 1,5l",K,0.99,20.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
1,2,ZÁLOHA PET,K,0.15,0.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-11-22 12:15:34,1,1,b'\x00'
2,3,"MAG.GREP 1,5l",K,0.65,20.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
3,4,"MAG.PER.1,5l",K,0.59,20.0,drinks/mineral-water,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
4,5,Raciol rastl.1l,K,2.59,20.0,basic/oil-acid-grease,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6742,6747,Sanytol uni.sprej 500ml,K,3.65,20.0,home/cleaning,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6743,6748,S&S KU 2x140 útrž.,K,1.25,20.0,home/cleaning,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6744,6749,Dettol antibak.obrús 80ks,K,6.65,20.0,health/vitamins-ointments,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6745,6750,"babylove vlh.ut. 99%vody,80",K,1.75,20.0,baby/supplies-hygiene,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6746,6751,xkko froté obrúsky biele 6k,K,6.95,20.0,home/maintenence,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'