In [1]:
import pandas as pd

In [4]:
producst_df = pd.read_csv("Products.csv")
producst_df["name"] = producst_df["name"].str.strip()
producst_df

,id,name,item_type,price,vat_rate,category,organization_id,org_unit_id,created_date,last_modified_date,created_by,last_modified_by,is_overridden
0,1,"NESTEA CITRÓN 1,5l",K,0.99,20.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
1,2,ZÁLOHA PET,K,0.15,0.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-11-22 12:15:34,1,1,b'\x00'
2,3,"MAG.GREP 1,5l",K,0.65,20.0,drinks/non-alcoholic,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
3,4,"MAG.PER.1,5l",K,0.59,20.0,drinks/mineral-water,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
4,5,Raciol rastl.1l,K,2.59,20.0,basic/oil-acid-grease,1,1,2023-09-28 22:57:45,2023-09-28 22:57:46,1,1,b'\x00'
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6742,6747,Sanytol uni.sprej 500ml,K,3.65,20.0,home/cleaning,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6743,6748,S&S KU 2x140 útrž.,K,1.25,20.0,home/cleaning,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6744,6749,Dettol antibak.obrús 80ks,K,6.65,20.0,health/vitamins-ointments,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6745,6750,"babylove vlh.ut. 99%vody,80",K,1.75,20.0,baby/supplies-hygiene,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'
6746,6751,xkko froté obrúsky biele 6k,K,6.95,20.0,home/maintenence,16,49,2024-11-07 11:10:22,2024-11-07 11:10:22,7,system,b'\x00'

In [6]:
producst_df.groupby('created_date')['name'].agg(', '.join).reset_index()["name"]

0      NESTEA CITRÓN 1,5l, ZÁLOHA PET, MAG.GREP 1,5l,...
1      K.Monorola 100m 1ks, Zľava s kupónom, Frisk. F...
2      Kinder surp. die.20g, Kokos.kmeň100g, Princezk...
3      FUZ.BROS.1,5l, KAČICA PITVANÁ, ZĽAVA PRE ČLENA...
4      ris.diav.350g, TP TENTO ECON.2-VR, DŽÚS HAP.DA...
                             ...
933                                   Parkovné za 30 min
934                               chrumkava kačica, Ryža
935    TESA 58570 transparent, TESA Basic 58549 Lepia...
936    Horalky, 50g, Fidorka kokos, Líz. Cola Lemon, ...
937    Sanytol antibakt.mydlo 250m, Dontodent zub.kef...
Name: name, Length: 938, dtype: object